package pl.modules;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class Name {
	private List<String> maleNames = new ArrayList<String>();
	private List<String> femaleNames = new ArrayList<String>();
	
	public String getMaleName() {
		prepareMaleNames();
		int max = maleNames.size() - 1;
		int random = ThreadLocalRandom.current().nextInt(0, max);
		String name = maleNames.get(random);
		return name;
	}
	
	public String getFemaleName() {
		prepareFemaleNames();
		int max = femaleNames.size() - 1;
		int random = ThreadLocalRandom.current().nextInt(0, max);
		String name = femaleNames.get(random);
		return name;
	}
		
	private void prepareMaleNames() {
		maleNames.add("Jan");
		maleNames.add("Antoni");
		maleNames.add("Franciszek");
		maleNames.add("Jakub");
		maleNames.add("Szymon");
		maleNames.add("Wojciech");
		maleNames.add("Aleksander");
		maleNames.add("Piotr");
		maleNames.add("Adam");
		maleNames.add("Kacper");
		maleNames.add("Mikołaj");
		maleNames.add("Michał");
		maleNames.add("Mateusz");
		maleNames.add("Leon");
		maleNames.add("Filip");
		maleNames.add("Marcel");
		maleNames.add("Stanisław");
		maleNames.add("Wiktor");
		maleNames.add("Miłosz");
		maleNames.add("Tomasz");
		maleNames.add("Karol");
		maleNames.add("Maksymilian");
		maleNames.add("Tymon");
		maleNames.add("Bartek");
		maleNames.add("Maciej");
		maleNames.add("Ignacy");
		maleNames.add("Krzysztof");
		maleNames.add("Gabriel");
		maleNames.add("Igor");
		maleNames.add("Julian");
		maleNames.add("Łukasz");
		maleNames.add("Patryk");
		maleNames.add("Tadeusz");
		maleNames.add("Dawid");
		maleNames.add("Kajetan");
		maleNames.add("Mieszko");
		maleNames.add("Ryszard");
		maleNames.add("Borys");
		maleNames.add("Dominik");
		maleNames.add("Gustaw");
		maleNames.add("Jerzy");
		maleNames.add("Ksawery");
		maleNames.add("Oliwier");
		maleNames.add("Oskar");
		maleNames.add("Tymoteusz");
		maleNames.add("Alan");
		maleNames.add("Artur");
		maleNames.add("Fabian");
		maleNames.add("Henryk");
		maleNames.add("Krystian");
		maleNames.add("Leonard");
		maleNames.add("Nikodem");
		maleNames.add("Olaf");
		maleNames.add("Paweł");
		maleNames.add("Sebastian");
		maleNames.add("Stefan");
		maleNames.add("Teodor");
		maleNames.add("Bruno");
		maleNames.add("Cezary");
		maleNames.add("Daniel");
		maleNames.add("Grzegorz");
		maleNames.add("Hubert");
		maleNames.add("Jeremi");
		maleNames.add("Kamil");
		maleNames.add("Kazimierz");
		maleNames.add("Maks");
		maleNames.add("Marek");
		maleNames.add("Robert");
		maleNames.add("Witold");
		maleNames.add("Adrian");
		maleNames.add("Arkadiusz");
		maleNames.add("Bolesław");
		maleNames.add("Feliks");
		maleNames.add("Hugo");
		maleNames.add("Jacek");
		maleNames.add("Juliusz");
		maleNames.add("Konstanty");
		maleNames.add("Leopold");
		maleNames.add("Ludwik");
		maleNames.add("Marcin");
		maleNames.add("Milan");
		maleNames.add("Radosław");
		maleNames.add("Seweryn");
		maleNames.add("Alex");
		maleNames.add("Anatol");
		maleNames.add("Andrzej");
		maleNames.add("Beniamin");
		maleNames.add("Bernard");
		maleNames.add("Błażej");
		maleNames.add("Bogdan");
		maleNames.add("Czesław");
		maleNames.add("Dorian");
		maleNames.add("Emil");
		maleNames.add("Ernest");
		maleNames.add("Gaspar");
		maleNames.add("Gniewomir");
		maleNames.add("Ireneusz");
		maleNames.add("Janusz");
		maleNames.add("Jeremiasz");
		maleNames.add("Jędrzej");
		maleNames.add("Józef");
		maleNames.add("Konrad");
		maleNames.add("Kornel");
		maleNames.add("Korneliusz");
		maleNames.add("Ksawier");
		maleNames.add("Lucjan");
		maleNames.add("Marceli");
		maleNames.add("Mariusz");
		maleNames.add("Natan");
		maleNames.add("Olgierd");
		maleNames.add("Radzimir");
		maleNames.add("Rafał");
		maleNames.add("Remigiusz");
		maleNames.add("Tobiasz");
		maleNames.add("Wincenty");
		maleNames.add("Władysław");

	}
	
	private void prepareFemaleNames() {
		femaleNames.add("Zofia");
		femaleNames.add("Maja");
		femaleNames.add("Alicja");
		femaleNames.add("Julia");
		femaleNames.add("Zuzanna");
		femaleNames.add("Amelia");
		femaleNames.add("Hanna");
		femaleNames.add("Oliwia");
		femaleNames.add("Aleksandra");
		femaleNames.add("Maria");
		femaleNames.add("Antonina");
		femaleNames.add("Liliana");
		femaleNames.add("Lena");
		femaleNames.add("Natalia");
		femaleNames.add("Pola");
		femaleNames.add("Gabriela");
		femaleNames.add("Laura");
		femaleNames.add("Anna");
		femaleNames.add("Helena");
		femaleNames.add("Joanna");
		femaleNames.add("Marcelina");
		femaleNames.add("Michalina");
		femaleNames.add("Łucja");
		femaleNames.add("Nina");
		femaleNames.add("Wiktoria");
		femaleNames.add("Aniela");
		femaleNames.add("Iga");
		femaleNames.add("Karolina");
		femaleNames.add("Magdalena");
		femaleNames.add("Kornelia");
		femaleNames.add("Marta");
		femaleNames.add("Blanka");
		femaleNames.add("Emilia");
		femaleNames.add("Martyna");
		femaleNames.add("Weronika");
		femaleNames.add("Agata");
		femaleNames.add("Aurelia");
		femaleNames.add("Nikola");
		femaleNames.add("Paulina");
		femaleNames.add("Sara");
		femaleNames.add("Bianka");
		femaleNames.add("Gaja");
		femaleNames.add("Kalina");
		femaleNames.add("Klara");
		femaleNames.add("Nadia");
		femaleNames.add("Róża");
		femaleNames.add("Ewa");
		femaleNames.add("Kaja");
		femaleNames.add("Karina");
		femaleNames.add("Katarzyna");
		femaleNames.add("Lidia");
		femaleNames.add("Marianna");
		femaleNames.add("Matylda");
		femaleNames.add("Nela");
		femaleNames.add("Rozalia");
		femaleNames.add("Adela");
		femaleNames.add("Barbara");
		femaleNames.add("Danuta");
		femaleNames.add("Dominika");
		femaleNames.add("Dorota");
		femaleNames.add("Eliza");
		femaleNames.add("Jagoda");
		femaleNames.add("Janina");
		femaleNames.add("Kamila");
		femaleNames.add("Kinga");
		femaleNames.add("Klaudia");
		femaleNames.add("Liwia");
		femaleNames.add("Małgorzata");
		femaleNames.add("Melania");
		femaleNames.add("Milena");
		femaleNames.add("Monika");
		femaleNames.add("Patrycja");
		femaleNames.add("Wanda");
		femaleNames.add("Adrianna");
		femaleNames.add("Agnieszka");
		femaleNames.add("Antonia");
		femaleNames.add("Apolonia");
		femaleNames.add("Aria");
		femaleNames.add("Celina");
		femaleNames.add("Dagmara");
		femaleNames.add("Daria");
		femaleNames.add("Dobrawa");
		femaleNames.add("Elżbieta");
		femaleNames.add("Emma");
		femaleNames.add("Ewelina");
		femaleNames.add("Gloria");
		femaleNames.add("Izabela");
		femaleNames.add("Jadwiga");
		femaleNames.add("Jagna");
		femaleNames.add("Jaśmina");
		femaleNames.add("Judyta");
		femaleNames.add("Konstancja");
		femaleNames.add("Krystyna");
		femaleNames.add("Lilia");
		femaleNames.add("Mia");
		femaleNames.add("Nel");
		femaleNames.add("Nelly");
		femaleNames.add("Rebeka");
		femaleNames.add("Rita");
		femaleNames.add("Sandra");
		femaleNames.add("Tola");
		femaleNames.add("Urszula");
	}

}
